server:
  port: 8090
#注册到Eureka服务中心
eureka:
  client:
    service-url:
      # 注册集群 就把多个EurekaServer地址使用逗号拼接起来，注册到单实力（非集群模式）就写一个就ok
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka,http://LagouCloudEurekaServerB:8762/eureka
    #使⽤ip注册，否则会使⽤主机名注册了（此处考虑到对⽼版本的兼容，新版本经过实验都是ip）
  instance:
    #⾃定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是
    ipAddress
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}:@project.version@
spring:
  application:
    name: Lagou-service-autodeliver